linear_method_srcs = \
linear_method.cc computation_node.cc scheduler.cc \
ftrl_scheduler.cc ftrl_worker.cc \


# batch_scheduler.cc batch_server.cc batch_worker.cc \
# darlin_scheduler.cc darlin_server.cc darlin_worker.cc \
# batch_solver.cc darling.cc
