TESTS = \
	stream_reader_test \
	slot_reader_test \
	matrix_io_test \
	localizer_test \
	countmin_test \
	snappy_test \
	shared_array_test \
	grad_desc_test \
	ftrl_test \
	prepare_test_data \
	bloom_filter_test \
	# test
	# sparse_matrix_perf \
	auc_test \
	io_test \
	bitmap_test \
	eigen3_test \
	sparse_matrix_test \
	auc_layer_test \
	# double_test \
	# aggregated_gradient_test \
	# strtonum_test
	#partition_test
	# van_test \
	# customer_test \
	# vectors_test \
        sparse_matrix_multi_thread_perf \
	fault_tolerance_press \
