// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/config.proto

#ifndef PROTOBUF_proto_2fconfig_2eproto__INCLUDED
#define PROTOBUF_proto_2fconfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "proto/range.pb.h"
// @@protoc_insertion_point(includes)

namespace PS {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_proto_2fconfig_2eproto();
void protobuf_AssignDesc_proto_2fconfig_2eproto();
void protobuf_ShutdownFile_proto_2fconfig_2eproto();

class AppConfig;
class DataConfig;
class ParameterInitConfig;
class BlockIteratorConfig;
class BlockCoordL1LRConfig;
class LossConfig;
class LearnerConfig;
class AggGradLearnerArg;
class PenaltyConfig;

enum AppConfig_AppType {
  AppConfig_AppType_RISK_MINIMIZATION = 1,
  AppConfig_AppType_SKETCH = 2
};
bool AppConfig_AppType_IsValid(int value);
const AppConfig_AppType AppConfig_AppType_AppType_MIN = AppConfig_AppType_RISK_MINIMIZATION;
const AppConfig_AppType AppConfig_AppType_AppType_MAX = AppConfig_AppType_SKETCH;
const int AppConfig_AppType_AppType_ARRAYSIZE = AppConfig_AppType_AppType_MAX + 1;

const ::google::protobuf::EnumDescriptor* AppConfig_AppType_descriptor();
inline const ::std::string& AppConfig_AppType_Name(AppConfig_AppType value) {
  return ::google::protobuf::internal::NameOfEnum(
    AppConfig_AppType_descriptor(), value);
}
inline bool AppConfig_AppType_Parse(
    const ::std::string& name, AppConfig_AppType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AppConfig_AppType>(
    AppConfig_AppType_descriptor(), name, value);
}
enum DataConfig_DataFormat {
  DataConfig_DataFormat_BIN = 1,
  DataConfig_DataFormat_PROTO = 2,
  DataConfig_DataFormat_TEXT = 3
};
bool DataConfig_DataFormat_IsValid(int value);
const DataConfig_DataFormat DataConfig_DataFormat_DataFormat_MIN = DataConfig_DataFormat_BIN;
const DataConfig_DataFormat DataConfig_DataFormat_DataFormat_MAX = DataConfig_DataFormat_TEXT;
const int DataConfig_DataFormat_DataFormat_ARRAYSIZE = DataConfig_DataFormat_DataFormat_MAX + 1;

const ::google::protobuf::EnumDescriptor* DataConfig_DataFormat_descriptor();
inline const ::std::string& DataConfig_DataFormat_Name(DataConfig_DataFormat value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataConfig_DataFormat_descriptor(), value);
}
inline bool DataConfig_DataFormat_Parse(
    const ::std::string& name, DataConfig_DataFormat* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataConfig_DataFormat>(
    DataConfig_DataFormat_descriptor(), name, value);
}
enum ParameterInitConfig_Type {
  ParameterInitConfig_Type_ZERO = 1,
  ParameterInitConfig_Type_RANDOM = 2,
  ParameterInitConfig_Type_FILE = 3
};
bool ParameterInitConfig_Type_IsValid(int value);
const ParameterInitConfig_Type ParameterInitConfig_Type_Type_MIN = ParameterInitConfig_Type_ZERO;
const ParameterInitConfig_Type ParameterInitConfig_Type_Type_MAX = ParameterInitConfig_Type_FILE;
const int ParameterInitConfig_Type_Type_ARRAYSIZE = ParameterInitConfig_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* ParameterInitConfig_Type_descriptor();
inline const ::std::string& ParameterInitConfig_Type_Name(ParameterInitConfig_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    ParameterInitConfig_Type_descriptor(), value);
}
inline bool ParameterInitConfig_Type_Parse(
    const ::std::string& name, ParameterInitConfig_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ParameterInitConfig_Type>(
    ParameterInitConfig_Type_descriptor(), name, value);
}
enum LossConfig_Type {
  LossConfig_Type_SQUARE = 1,
  LossConfig_Type_LOGIT = 2,
  LossConfig_Type_HINGE = 3,
  LossConfig_Type_SQUARE_HINGE = 4
};
bool LossConfig_Type_IsValid(int value);
const LossConfig_Type LossConfig_Type_Type_MIN = LossConfig_Type_SQUARE;
const LossConfig_Type LossConfig_Type_Type_MAX = LossConfig_Type_SQUARE_HINGE;
const int LossConfig_Type_Type_ARRAYSIZE = LossConfig_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* LossConfig_Type_descriptor();
inline const ::std::string& LossConfig_Type_Name(LossConfig_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    LossConfig_Type_descriptor(), value);
}
inline bool LossConfig_Type_Parse(
    const ::std::string& name, LossConfig_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LossConfig_Type>(
    LossConfig_Type_descriptor(), name, value);
}
enum LearnerConfig_Type {
  LearnerConfig_Type_GRADIENT_DESCENT = 1,
  LearnerConfig_Type_PROXIMAL_GRADIENT = 2,
  LearnerConfig_Type_LBFGS = 3
};
bool LearnerConfig_Type_IsValid(int value);
const LearnerConfig_Type LearnerConfig_Type_Type_MIN = LearnerConfig_Type_GRADIENT_DESCENT;
const LearnerConfig_Type LearnerConfig_Type_Type_MAX = LearnerConfig_Type_LBFGS;
const int LearnerConfig_Type_Type_ARRAYSIZE = LearnerConfig_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* LearnerConfig_Type_descriptor();
inline const ::std::string& LearnerConfig_Type_Name(LearnerConfig_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    LearnerConfig_Type_descriptor(), value);
}
inline bool LearnerConfig_Type_Parse(
    const ::std::string& name, LearnerConfig_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LearnerConfig_Type>(
    LearnerConfig_Type_descriptor(), name, value);
}
enum PenaltyConfig_Type {
  PenaltyConfig_Type_L1 = 1,
  PenaltyConfig_Type_L2 = 2
};
bool PenaltyConfig_Type_IsValid(int value);
const PenaltyConfig_Type PenaltyConfig_Type_Type_MIN = PenaltyConfig_Type_L1;
const PenaltyConfig_Type PenaltyConfig_Type_Type_MAX = PenaltyConfig_Type_L2;
const int PenaltyConfig_Type_Type_ARRAYSIZE = PenaltyConfig_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* PenaltyConfig_Type_descriptor();
inline const ::std::string& PenaltyConfig_Type_Name(PenaltyConfig_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    PenaltyConfig_Type_descriptor(), value);
}
inline bool PenaltyConfig_Type_Parse(
    const ::std::string& name, PenaltyConfig_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PenaltyConfig_Type>(
    PenaltyConfig_Type_descriptor(), name, value);
}
// ===================================================================

class AppConfig : public ::google::protobuf::Message {
 public:
  AppConfig();
  virtual ~AppConfig();

  AppConfig(const AppConfig& from);

  inline AppConfig& operator=(const AppConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AppConfig& default_instance();

  void Swap(AppConfig* other);

  // implements Message ----------------------------------------------

  AppConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AppConfig& from);
  void MergeFrom(const AppConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef AppConfig_AppType AppType;
  static const AppType RISK_MINIMIZATION = AppConfig_AppType_RISK_MINIMIZATION;
  static const AppType SKETCH = AppConfig_AppType_SKETCH;
  static inline bool AppType_IsValid(int value) {
    return AppConfig_AppType_IsValid(value);
  }
  static const AppType AppType_MIN =
    AppConfig_AppType_AppType_MIN;
  static const AppType AppType_MAX =
    AppConfig_AppType_AppType_MAX;
  static const int AppType_ARRAYSIZE =
    AppConfig_AppType_AppType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  AppType_descriptor() {
    return AppConfig_AppType_descriptor();
  }
  static inline const ::std::string& AppType_Name(AppType value) {
    return AppConfig_AppType_Name(value);
  }
  static inline bool AppType_Parse(const ::std::string& name,
      AppType* value) {
    return AppConfig_AppType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .PS.AppConfig.AppType type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::PS::AppConfig_AppType type() const;
  inline void set_type(::PS::AppConfig_AppType value);

  // optional string app_name = 2;
  inline bool has_app_name() const;
  inline void clear_app_name();
  static const int kAppNameFieldNumber = 2;
  inline const ::std::string& app_name() const;
  inline void set_app_name(const ::std::string& value);
  inline void set_app_name(const char* value);
  inline void set_app_name(const char* value, size_t size);
  inline ::std::string* mutable_app_name();
  inline ::std::string* release_app_name();
  inline void set_allocated_app_name(::std::string* app_name);

  // repeated string parameter_name = 3;
  inline int parameter_name_size() const;
  inline void clear_parameter_name();
  static const int kParameterNameFieldNumber = 3;
  inline const ::std::string& parameter_name(int index) const;
  inline ::std::string* mutable_parameter_name(int index);
  inline void set_parameter_name(int index, const ::std::string& value);
  inline void set_parameter_name(int index, const char* value);
  inline void set_parameter_name(int index, const char* value, size_t size);
  inline ::std::string* add_parameter_name();
  inline void add_parameter_name(const ::std::string& value);
  inline void add_parameter_name(const char* value);
  inline void add_parameter_name(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& parameter_name() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_parameter_name();

  // optional .PS.DataConfig training = 10;
  inline bool has_training() const;
  inline void clear_training();
  static const int kTrainingFieldNumber = 10;
  inline const ::PS::DataConfig& training() const;
  inline ::PS::DataConfig* mutable_training();
  inline ::PS::DataConfig* release_training();
  inline void set_allocated_training(::PS::DataConfig* training);

  // optional .PS.ParameterInitConfig init_w = 13;
  inline bool has_init_w() const;
  inline void clear_init_w();
  static const int kInitWFieldNumber = 13;
  inline const ::PS::ParameterInitConfig& init_w() const;
  inline ::PS::ParameterInitConfig* mutable_init_w();
  inline ::PS::ParameterInitConfig* release_init_w();
  inline void set_allocated_init_w(::PS::ParameterInitConfig* init_w);

  // optional .PS.DataConfig model_output = 15;
  inline bool has_model_output() const;
  inline void clear_model_output();
  static const int kModelOutputFieldNumber = 15;
  inline const ::PS::DataConfig& model_output() const;
  inline ::PS::DataConfig* mutable_model_output();
  inline ::PS::DataConfig* release_model_output();
  inline void set_allocated_model_output(::PS::DataConfig* model_output);

  // optional .PS.LossConfig loss = 20;
  inline bool has_loss() const;
  inline void clear_loss();
  static const int kLossFieldNumber = 20;
  inline const ::PS::LossConfig& loss() const;
  inline ::PS::LossConfig* mutable_loss();
  inline ::PS::LossConfig* release_loss();
  inline void set_allocated_loss(::PS::LossConfig* loss);

  // optional .PS.PenaltyConfig penalty = 21;
  inline bool has_penalty() const;
  inline void clear_penalty();
  static const int kPenaltyFieldNumber = 21;
  inline const ::PS::PenaltyConfig& penalty() const;
  inline ::PS::PenaltyConfig* mutable_penalty();
  inline ::PS::PenaltyConfig* release_penalty();
  inline void set_allocated_penalty(::PS::PenaltyConfig* penalty);

  // optional .PS.LearnerConfig learner = 30;
  inline bool has_learner() const;
  inline void clear_learner();
  static const int kLearnerFieldNumber = 30;
  inline const ::PS::LearnerConfig& learner() const;
  inline ::PS::LearnerConfig* mutable_learner();
  inline ::PS::LearnerConfig* release_learner();
  inline void set_allocated_learner(::PS::LearnerConfig* learner);

  // optional .PS.BlockIteratorConfig block_iterator = 40;
  inline bool has_block_iterator() const;
  inline void clear_block_iterator();
  static const int kBlockIteratorFieldNumber = 40;
  inline const ::PS::BlockIteratorConfig& block_iterator() const;
  inline ::PS::BlockIteratorConfig* mutable_block_iterator();
  inline ::PS::BlockIteratorConfig* release_block_iterator();
  inline void set_allocated_block_iterator(::PS::BlockIteratorConfig* block_iterator);

  // optional .PS.BlockCoordL1LRConfig block_coord_l1lr = 41;
  inline bool has_block_coord_l1lr() const;
  inline void clear_block_coord_l1lr();
  static const int kBlockCoordL1LrFieldNumber = 41;
  inline const ::PS::BlockCoordL1LRConfig& block_coord_l1lr() const;
  inline ::PS::BlockCoordL1LRConfig* mutable_block_coord_l1lr();
  inline ::PS::BlockCoordL1LRConfig* release_block_coord_l1lr();
  inline void set_allocated_block_coord_l1lr(::PS::BlockCoordL1LRConfig* block_coord_l1lr);

  // @@protoc_insertion_point(class_scope:PS.AppConfig)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_app_name();
  inline void clear_has_app_name();
  inline void set_has_training();
  inline void clear_has_training();
  inline void set_has_init_w();
  inline void clear_has_init_w();
  inline void set_has_model_output();
  inline void clear_has_model_output();
  inline void set_has_loss();
  inline void clear_has_loss();
  inline void set_has_penalty();
  inline void clear_has_penalty();
  inline void set_has_learner();
  inline void clear_has_learner();
  inline void set_has_block_iterator();
  inline void clear_has_block_iterator();
  inline void set_has_block_coord_l1lr();
  inline void clear_has_block_coord_l1lr();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* app_name_;
  ::google::protobuf::RepeatedPtrField< ::std::string> parameter_name_;
  ::PS::DataConfig* training_;
  ::PS::ParameterInitConfig* init_w_;
  ::PS::DataConfig* model_output_;
  ::PS::LossConfig* loss_;
  ::PS::PenaltyConfig* penalty_;
  ::PS::LearnerConfig* learner_;
  ::PS::BlockIteratorConfig* block_iterator_;
  ::PS::BlockCoordL1LRConfig* block_coord_l1lr_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(11 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fconfig_2eproto();
  friend void protobuf_AssignDesc_proto_2fconfig_2eproto();
  friend void protobuf_ShutdownFile_proto_2fconfig_2eproto();

  void InitAsDefaultInstance();
  static AppConfig* default_instance_;
};
// -------------------------------------------------------------------

class DataConfig : public ::google::protobuf::Message {
 public:
  DataConfig();
  virtual ~DataConfig();

  DataConfig(const DataConfig& from);

  inline DataConfig& operator=(const DataConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DataConfig& default_instance();

  void Swap(DataConfig* other);

  // implements Message ----------------------------------------------

  DataConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DataConfig& from);
  void MergeFrom(const DataConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef DataConfig_DataFormat DataFormat;
  static const DataFormat BIN = DataConfig_DataFormat_BIN;
  static const DataFormat PROTO = DataConfig_DataFormat_PROTO;
  static const DataFormat TEXT = DataConfig_DataFormat_TEXT;
  static inline bool DataFormat_IsValid(int value) {
    return DataConfig_DataFormat_IsValid(value);
  }
  static const DataFormat DataFormat_MIN =
    DataConfig_DataFormat_DataFormat_MIN;
  static const DataFormat DataFormat_MAX =
    DataConfig_DataFormat_DataFormat_MAX;
  static const int DataFormat_ARRAYSIZE =
    DataConfig_DataFormat_DataFormat_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  DataFormat_descriptor() {
    return DataConfig_DataFormat_descriptor();
  }
  static inline const ::std::string& DataFormat_Name(DataFormat value) {
    return DataConfig_DataFormat_Name(value);
  }
  static inline bool DataFormat_Parse(const ::std::string& name,
      DataFormat* value) {
    return DataConfig_DataFormat_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .PS.DataConfig.DataFormat format = 1;
  inline bool has_format() const;
  inline void clear_format();
  static const int kFormatFieldNumber = 1;
  inline ::PS::DataConfig_DataFormat format() const;
  inline void set_format(::PS::DataConfig_DataFormat value);

  // repeated string files = 2;
  inline int files_size() const;
  inline void clear_files();
  static const int kFilesFieldNumber = 2;
  inline const ::std::string& files(int index) const;
  inline ::std::string* mutable_files(int index);
  inline void set_files(int index, const ::std::string& value);
  inline void set_files(int index, const char* value);
  inline void set_files(int index, const char* value, size_t size);
  inline ::std::string* add_files();
  inline void add_files(const ::std::string& value);
  inline void add_files(const char* value);
  inline void add_files(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& files() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_files();

  // optional .PS.PbRange range = 3;
  inline bool has_range() const;
  inline void clear_range();
  static const int kRangeFieldNumber = 3;
  inline const ::PS::PbRange& range() const;
  inline ::PS::PbRange* mutable_range();
  inline ::PS::PbRange* release_range();
  inline void set_allocated_range(::PS::PbRange* range);

  // @@protoc_insertion_point(class_scope:PS.DataConfig)
 private:
  inline void set_has_format();
  inline void clear_has_format();
  inline void set_has_range();
  inline void clear_has_range();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> files_;
  ::PS::PbRange* range_;
  int format_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fconfig_2eproto();
  friend void protobuf_AssignDesc_proto_2fconfig_2eproto();
  friend void protobuf_ShutdownFile_proto_2fconfig_2eproto();

  void InitAsDefaultInstance();
  static DataConfig* default_instance_;
};
// -------------------------------------------------------------------

class ParameterInitConfig : public ::google::protobuf::Message {
 public:
  ParameterInitConfig();
  virtual ~ParameterInitConfig();

  ParameterInitConfig(const ParameterInitConfig& from);

  inline ParameterInitConfig& operator=(const ParameterInitConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ParameterInitConfig& default_instance();

  void Swap(ParameterInitConfig* other);

  // implements Message ----------------------------------------------

  ParameterInitConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ParameterInitConfig& from);
  void MergeFrom(const ParameterInitConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ParameterInitConfig_Type Type;
  static const Type ZERO = ParameterInitConfig_Type_ZERO;
  static const Type RANDOM = ParameterInitConfig_Type_RANDOM;
  static const Type FILE = ParameterInitConfig_Type_FILE;
  static inline bool Type_IsValid(int value) {
    return ParameterInitConfig_Type_IsValid(value);
  }
  static const Type Type_MIN =
    ParameterInitConfig_Type_Type_MIN;
  static const Type Type_MAX =
    ParameterInitConfig_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    ParameterInitConfig_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return ParameterInitConfig_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return ParameterInitConfig_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return ParameterInitConfig_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .PS.ParameterInitConfig.Type type = 1 [default = ZERO];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::PS::ParameterInitConfig_Type type() const;
  inline void set_type(::PS::ParameterInitConfig_Type value);

  // optional double random_std = 2 [default = 1];
  inline bool has_random_std() const;
  inline void clear_random_std();
  static const int kRandomStdFieldNumber = 2;
  inline double random_std() const;
  inline void set_random_std(double value);

  // @@protoc_insertion_point(class_scope:PS.ParameterInitConfig)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_random_std();
  inline void clear_has_random_std();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double random_std_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fconfig_2eproto();
  friend void protobuf_AssignDesc_proto_2fconfig_2eproto();
  friend void protobuf_ShutdownFile_proto_2fconfig_2eproto();

  void InitAsDefaultInstance();
  static ParameterInitConfig* default_instance_;
};
// -------------------------------------------------------------------

class BlockIteratorConfig : public ::google::protobuf::Message {
 public:
  BlockIteratorConfig();
  virtual ~BlockIteratorConfig();

  BlockIteratorConfig(const BlockIteratorConfig& from);

  inline BlockIteratorConfig& operator=(const BlockIteratorConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BlockIteratorConfig& default_instance();

  void Swap(BlockIteratorConfig* other);

  // implements Message ----------------------------------------------

  BlockIteratorConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BlockIteratorConfig& from);
  void MergeFrom(const BlockIteratorConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 example_block_size = 1 [default = -1];
  inline bool has_example_block_size() const;
  inline void clear_example_block_size();
  static const int kExampleBlockSizeFieldNumber = 1;
  inline ::google::protobuf::int64 example_block_size() const;
  inline void set_example_block_size(::google::protobuf::int64 value);

  // optional float feature_block_ratio = 2 [default = 0];
  inline bool has_feature_block_ratio() const;
  inline void clear_feature_block_ratio();
  static const int kFeatureBlockRatioFieldNumber = 2;
  inline float feature_block_ratio() const;
  inline void set_feature_block_ratio(float value);

  // optional bool random_feature_block_order = 3 [default = true];
  inline bool has_random_feature_block_order() const;
  inline void clear_random_feature_block_order();
  static const int kRandomFeatureBlockOrderFieldNumber = 3;
  inline bool random_feature_block_order() const;
  inline void set_random_feature_block_order(bool value);

  // optional int32 max_pass_of_data = 8 [default = 10];
  inline bool has_max_pass_of_data() const;
  inline void clear_max_pass_of_data();
  static const int kMaxPassOfDataFieldNumber = 8;
  inline ::google::protobuf::int32 max_pass_of_data() const;
  inline void set_max_pass_of_data(::google::protobuf::int32 value);

  // optional int32 max_block_delay = 10 [default = 0];
  inline bool has_max_block_delay() const;
  inline void clear_max_block_delay();
  static const int kMaxBlockDelayFieldNumber = 10;
  inline ::google::protobuf::int32 max_block_delay() const;
  inline void set_max_block_delay(::google::protobuf::int32 value);

  // optional double epsilon = 11 [default = 0.0001];
  inline bool has_epsilon() const;
  inline void clear_epsilon();
  static const int kEpsilonFieldNumber = 11;
  inline double epsilon() const;
  inline void set_epsilon(double value);

  // @@protoc_insertion_point(class_scope:PS.BlockIteratorConfig)
 private:
  inline void set_has_example_block_size();
  inline void clear_has_example_block_size();
  inline void set_has_feature_block_ratio();
  inline void clear_has_feature_block_ratio();
  inline void set_has_random_feature_block_order();
  inline void clear_has_random_feature_block_order();
  inline void set_has_max_pass_of_data();
  inline void clear_has_max_pass_of_data();
  inline void set_has_max_block_delay();
  inline void clear_has_max_block_delay();
  inline void set_has_epsilon();
  inline void clear_has_epsilon();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 example_block_size_;
  float feature_block_ratio_;
  bool random_feature_block_order_;
  ::google::protobuf::int32 max_pass_of_data_;
  ::google::protobuf::int32 max_block_delay_;
  double epsilon_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fconfig_2eproto();
  friend void protobuf_AssignDesc_proto_2fconfig_2eproto();
  friend void protobuf_ShutdownFile_proto_2fconfig_2eproto();

  void InitAsDefaultInstance();
  static BlockIteratorConfig* default_instance_;
};
// -------------------------------------------------------------------

class BlockCoordL1LRConfig : public ::google::protobuf::Message {
 public:
  BlockCoordL1LRConfig();
  virtual ~BlockCoordL1LRConfig();

  BlockCoordL1LRConfig(const BlockCoordL1LRConfig& from);

  inline BlockCoordL1LRConfig& operator=(const BlockCoordL1LRConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BlockCoordL1LRConfig& default_instance();

  void Swap(BlockCoordL1LRConfig* other);

  // implements Message ----------------------------------------------

  BlockCoordL1LRConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BlockCoordL1LRConfig& from);
  void MergeFrom(const BlockCoordL1LRConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double delta_init_value = 1 [default = 1];
  inline bool has_delta_init_value() const;
  inline void clear_delta_init_value();
  static const int kDeltaInitValueFieldNumber = 1;
  inline double delta_init_value() const;
  inline void set_delta_init_value(double value);

  // optional double delta_max_value = 2 [default = 5];
  inline bool has_delta_max_value() const;
  inline void clear_delta_max_value();
  static const int kDeltaMaxValueFieldNumber = 2;
  inline double delta_max_value() const;
  inline void set_delta_max_value(double value);

  // optional bool enable_multi_thread = 4 [default = false];
  inline bool has_enable_multi_thread() const;
  inline void clear_enable_multi_thread();
  static const int kEnableMultiThreadFieldNumber = 4;
  inline bool enable_multi_thread() const;
  inline void set_enable_multi_thread(bool value);

  // optional double kkt_filter_threshold_ratio = 10 [default = 10];
  inline bool has_kkt_filter_threshold_ratio() const;
  inline void clear_kkt_filter_threshold_ratio();
  static const int kKktFilterThresholdRatioFieldNumber = 10;
  inline double kkt_filter_threshold_ratio() const;
  inline void set_kkt_filter_threshold_ratio(double value);

  // optional int64 auc_goodness = 12 [default = 1000];
  inline bool has_auc_goodness() const;
  inline void clear_auc_goodness();
  static const int kAucGoodnessFieldNumber = 12;
  inline ::google::protobuf::int64 auc_goodness() const;
  inline void set_auc_goodness(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:PS.BlockCoordL1LRConfig)
 private:
  inline void set_has_delta_init_value();
  inline void clear_has_delta_init_value();
  inline void set_has_delta_max_value();
  inline void clear_has_delta_max_value();
  inline void set_has_enable_multi_thread();
  inline void clear_has_enable_multi_thread();
  inline void set_has_kkt_filter_threshold_ratio();
  inline void clear_has_kkt_filter_threshold_ratio();
  inline void set_has_auc_goodness();
  inline void clear_has_auc_goodness();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double delta_init_value_;
  double delta_max_value_;
  double kkt_filter_threshold_ratio_;
  ::google::protobuf::int64 auc_goodness_;
  bool enable_multi_thread_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fconfig_2eproto();
  friend void protobuf_AssignDesc_proto_2fconfig_2eproto();
  friend void protobuf_ShutdownFile_proto_2fconfig_2eproto();

  void InitAsDefaultInstance();
  static BlockCoordL1LRConfig* default_instance_;
};
// -------------------------------------------------------------------

class LossConfig : public ::google::protobuf::Message {
 public:
  LossConfig();
  virtual ~LossConfig();

  LossConfig(const LossConfig& from);

  inline LossConfig& operator=(const LossConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LossConfig& default_instance();

  void Swap(LossConfig* other);

  // implements Message ----------------------------------------------

  LossConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LossConfig& from);
  void MergeFrom(const LossConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef LossConfig_Type Type;
  static const Type SQUARE = LossConfig_Type_SQUARE;
  static const Type LOGIT = LossConfig_Type_LOGIT;
  static const Type HINGE = LossConfig_Type_HINGE;
  static const Type SQUARE_HINGE = LossConfig_Type_SQUARE_HINGE;
  static inline bool Type_IsValid(int value) {
    return LossConfig_Type_IsValid(value);
  }
  static const Type Type_MIN =
    LossConfig_Type_Type_MIN;
  static const Type Type_MAX =
    LossConfig_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    LossConfig_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return LossConfig_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return LossConfig_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return LossConfig_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .PS.LossConfig.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::PS::LossConfig_Type type() const;
  inline void set_type(::PS::LossConfig_Type value);

  // @@protoc_insertion_point(class_scope:PS.LossConfig)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fconfig_2eproto();
  friend void protobuf_AssignDesc_proto_2fconfig_2eproto();
  friend void protobuf_ShutdownFile_proto_2fconfig_2eproto();

  void InitAsDefaultInstance();
  static LossConfig* default_instance_;
};
// -------------------------------------------------------------------

class LearnerConfig : public ::google::protobuf::Message {
 public:
  LearnerConfig();
  virtual ~LearnerConfig();

  LearnerConfig(const LearnerConfig& from);

  inline LearnerConfig& operator=(const LearnerConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LearnerConfig& default_instance();

  void Swap(LearnerConfig* other);

  // implements Message ----------------------------------------------

  LearnerConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LearnerConfig& from);
  void MergeFrom(const LearnerConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef LearnerConfig_Type Type;
  static const Type GRADIENT_DESCENT = LearnerConfig_Type_GRADIENT_DESCENT;
  static const Type PROXIMAL_GRADIENT = LearnerConfig_Type_PROXIMAL_GRADIENT;
  static const Type LBFGS = LearnerConfig_Type_LBFGS;
  static inline bool Type_IsValid(int value) {
    return LearnerConfig_Type_IsValid(value);
  }
  static const Type Type_MIN =
    LearnerConfig_Type_Type_MIN;
  static const Type Type_MAX =
    LearnerConfig_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    LearnerConfig_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return LearnerConfig_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return LearnerConfig_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return LearnerConfig_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .PS.LearnerConfig.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::PS::LearnerConfig_Type type() const;
  inline void set_type(::PS::LearnerConfig_Type value);

  // optional float learning_rate = 2 [default = 1];
  inline bool has_learning_rate() const;
  inline void clear_learning_rate();
  static const int kLearningRateFieldNumber = 2;
  inline float learning_rate() const;
  inline void set_learning_rate(float value);

  // @@protoc_insertion_point(class_scope:PS.LearnerConfig)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_learning_rate();
  inline void clear_has_learning_rate();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int type_;
  float learning_rate_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fconfig_2eproto();
  friend void protobuf_AssignDesc_proto_2fconfig_2eproto();
  friend void protobuf_ShutdownFile_proto_2fconfig_2eproto();

  void InitAsDefaultInstance();
  static LearnerConfig* default_instance_;
};
// -------------------------------------------------------------------

class AggGradLearnerArg : public ::google::protobuf::Message {
 public:
  AggGradLearnerArg();
  virtual ~AggGradLearnerArg();

  AggGradLearnerArg(const AggGradLearnerArg& from);

  inline AggGradLearnerArg& operator=(const AggGradLearnerArg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AggGradLearnerArg& default_instance();

  void Swap(AggGradLearnerArg* other);

  // implements Message ----------------------------------------------

  AggGradLearnerArg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AggGradLearnerArg& from);
  void MergeFrom(const AggGradLearnerArg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float learning_rate = 1 [default = 1];
  inline bool has_learning_rate() const;
  inline void clear_learning_rate();
  static const int kLearningRateFieldNumber = 1;
  inline float learning_rate() const;
  inline void set_learning_rate(float value);

  // @@protoc_insertion_point(class_scope:PS.AggGradLearnerArg)
 private:
  inline void set_has_learning_rate();
  inline void clear_has_learning_rate();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  float learning_rate_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fconfig_2eproto();
  friend void protobuf_AssignDesc_proto_2fconfig_2eproto();
  friend void protobuf_ShutdownFile_proto_2fconfig_2eproto();

  void InitAsDefaultInstance();
  static AggGradLearnerArg* default_instance_;
};
// -------------------------------------------------------------------

class PenaltyConfig : public ::google::protobuf::Message {
 public:
  PenaltyConfig();
  virtual ~PenaltyConfig();

  PenaltyConfig(const PenaltyConfig& from);

  inline PenaltyConfig& operator=(const PenaltyConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PenaltyConfig& default_instance();

  void Swap(PenaltyConfig* other);

  // implements Message ----------------------------------------------

  PenaltyConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PenaltyConfig& from);
  void MergeFrom(const PenaltyConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef PenaltyConfig_Type Type;
  static const Type L1 = PenaltyConfig_Type_L1;
  static const Type L2 = PenaltyConfig_Type_L2;
  static inline bool Type_IsValid(int value) {
    return PenaltyConfig_Type_IsValid(value);
  }
  static const Type Type_MIN =
    PenaltyConfig_Type_Type_MIN;
  static const Type Type_MAX =
    PenaltyConfig_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    PenaltyConfig_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return PenaltyConfig_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return PenaltyConfig_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return PenaltyConfig_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .PS.PenaltyConfig.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::PS::PenaltyConfig_Type type() const;
  inline void set_type(::PS::PenaltyConfig_Type value);

  // required float coefficient = 2 [default = 0];
  inline bool has_coefficient() const;
  inline void clear_coefficient();
  static const int kCoefficientFieldNumber = 2;
  inline float coefficient() const;
  inline void set_coefficient(float value);

  // @@protoc_insertion_point(class_scope:PS.PenaltyConfig)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_coefficient();
  inline void clear_has_coefficient();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  int type_;
  float coefficient_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_proto_2fconfig_2eproto();
  friend void protobuf_AssignDesc_proto_2fconfig_2eproto();
  friend void protobuf_ShutdownFile_proto_2fconfig_2eproto();

  void InitAsDefaultInstance();
  static PenaltyConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// AppConfig

// optional .PS.AppConfig.AppType type = 1;
inline bool AppConfig::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AppConfig::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AppConfig::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AppConfig::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::PS::AppConfig_AppType AppConfig::type() const {
  return static_cast< ::PS::AppConfig_AppType >(type_);
}
inline void AppConfig::set_type(::PS::AppConfig_AppType value) {
  assert(::PS::AppConfig_AppType_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional string app_name = 2;
inline bool AppConfig::has_app_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AppConfig::set_has_app_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AppConfig::clear_has_app_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AppConfig::clear_app_name() {
  if (app_name_ != &::google::protobuf::internal::kEmptyString) {
    app_name_->clear();
  }
  clear_has_app_name();
}
inline const ::std::string& AppConfig::app_name() const {
  return *app_name_;
}
inline void AppConfig::set_app_name(const ::std::string& value) {
  set_has_app_name();
  if (app_name_ == &::google::protobuf::internal::kEmptyString) {
    app_name_ = new ::std::string;
  }
  app_name_->assign(value);
}
inline void AppConfig::set_app_name(const char* value) {
  set_has_app_name();
  if (app_name_ == &::google::protobuf::internal::kEmptyString) {
    app_name_ = new ::std::string;
  }
  app_name_->assign(value);
}
inline void AppConfig::set_app_name(const char* value, size_t size) {
  set_has_app_name();
  if (app_name_ == &::google::protobuf::internal::kEmptyString) {
    app_name_ = new ::std::string;
  }
  app_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AppConfig::mutable_app_name() {
  set_has_app_name();
  if (app_name_ == &::google::protobuf::internal::kEmptyString) {
    app_name_ = new ::std::string;
  }
  return app_name_;
}
inline ::std::string* AppConfig::release_app_name() {
  clear_has_app_name();
  if (app_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = app_name_;
    app_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void AppConfig::set_allocated_app_name(::std::string* app_name) {
  if (app_name_ != &::google::protobuf::internal::kEmptyString) {
    delete app_name_;
  }
  if (app_name) {
    set_has_app_name();
    app_name_ = app_name;
  } else {
    clear_has_app_name();
    app_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated string parameter_name = 3;
inline int AppConfig::parameter_name_size() const {
  return parameter_name_.size();
}
inline void AppConfig::clear_parameter_name() {
  parameter_name_.Clear();
}
inline const ::std::string& AppConfig::parameter_name(int index) const {
  return parameter_name_.Get(index);
}
inline ::std::string* AppConfig::mutable_parameter_name(int index) {
  return parameter_name_.Mutable(index);
}
inline void AppConfig::set_parameter_name(int index, const ::std::string& value) {
  parameter_name_.Mutable(index)->assign(value);
}
inline void AppConfig::set_parameter_name(int index, const char* value) {
  parameter_name_.Mutable(index)->assign(value);
}
inline void AppConfig::set_parameter_name(int index, const char* value, size_t size) {
  parameter_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AppConfig::add_parameter_name() {
  return parameter_name_.Add();
}
inline void AppConfig::add_parameter_name(const ::std::string& value) {
  parameter_name_.Add()->assign(value);
}
inline void AppConfig::add_parameter_name(const char* value) {
  parameter_name_.Add()->assign(value);
}
inline void AppConfig::add_parameter_name(const char* value, size_t size) {
  parameter_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
AppConfig::parameter_name() const {
  return parameter_name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
AppConfig::mutable_parameter_name() {
  return &parameter_name_;
}

// optional .PS.DataConfig training = 10;
inline bool AppConfig::has_training() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AppConfig::set_has_training() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AppConfig::clear_has_training() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AppConfig::clear_training() {
  if (training_ != NULL) training_->::PS::DataConfig::Clear();
  clear_has_training();
}
inline const ::PS::DataConfig& AppConfig::training() const {
  return training_ != NULL ? *training_ : *default_instance_->training_;
}
inline ::PS::DataConfig* AppConfig::mutable_training() {
  set_has_training();
  if (training_ == NULL) training_ = new ::PS::DataConfig;
  return training_;
}
inline ::PS::DataConfig* AppConfig::release_training() {
  clear_has_training();
  ::PS::DataConfig* temp = training_;
  training_ = NULL;
  return temp;
}
inline void AppConfig::set_allocated_training(::PS::DataConfig* training) {
  delete training_;
  training_ = training;
  if (training) {
    set_has_training();
  } else {
    clear_has_training();
  }
}

// optional .PS.ParameterInitConfig init_w = 13;
inline bool AppConfig::has_init_w() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AppConfig::set_has_init_w() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AppConfig::clear_has_init_w() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AppConfig::clear_init_w() {
  if (init_w_ != NULL) init_w_->::PS::ParameterInitConfig::Clear();
  clear_has_init_w();
}
inline const ::PS::ParameterInitConfig& AppConfig::init_w() const {
  return init_w_ != NULL ? *init_w_ : *default_instance_->init_w_;
}
inline ::PS::ParameterInitConfig* AppConfig::mutable_init_w() {
  set_has_init_w();
  if (init_w_ == NULL) init_w_ = new ::PS::ParameterInitConfig;
  return init_w_;
}
inline ::PS::ParameterInitConfig* AppConfig::release_init_w() {
  clear_has_init_w();
  ::PS::ParameterInitConfig* temp = init_w_;
  init_w_ = NULL;
  return temp;
}
inline void AppConfig::set_allocated_init_w(::PS::ParameterInitConfig* init_w) {
  delete init_w_;
  init_w_ = init_w;
  if (init_w) {
    set_has_init_w();
  } else {
    clear_has_init_w();
  }
}

// optional .PS.DataConfig model_output = 15;
inline bool AppConfig::has_model_output() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void AppConfig::set_has_model_output() {
  _has_bits_[0] |= 0x00000020u;
}
inline void AppConfig::clear_has_model_output() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void AppConfig::clear_model_output() {
  if (model_output_ != NULL) model_output_->::PS::DataConfig::Clear();
  clear_has_model_output();
}
inline const ::PS::DataConfig& AppConfig::model_output() const {
  return model_output_ != NULL ? *model_output_ : *default_instance_->model_output_;
}
inline ::PS::DataConfig* AppConfig::mutable_model_output() {
  set_has_model_output();
  if (model_output_ == NULL) model_output_ = new ::PS::DataConfig;
  return model_output_;
}
inline ::PS::DataConfig* AppConfig::release_model_output() {
  clear_has_model_output();
  ::PS::DataConfig* temp = model_output_;
  model_output_ = NULL;
  return temp;
}
inline void AppConfig::set_allocated_model_output(::PS::DataConfig* model_output) {
  delete model_output_;
  model_output_ = model_output;
  if (model_output) {
    set_has_model_output();
  } else {
    clear_has_model_output();
  }
}

// optional .PS.LossConfig loss = 20;
inline bool AppConfig::has_loss() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void AppConfig::set_has_loss() {
  _has_bits_[0] |= 0x00000040u;
}
inline void AppConfig::clear_has_loss() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void AppConfig::clear_loss() {
  if (loss_ != NULL) loss_->::PS::LossConfig::Clear();
  clear_has_loss();
}
inline const ::PS::LossConfig& AppConfig::loss() const {
  return loss_ != NULL ? *loss_ : *default_instance_->loss_;
}
inline ::PS::LossConfig* AppConfig::mutable_loss() {
  set_has_loss();
  if (loss_ == NULL) loss_ = new ::PS::LossConfig;
  return loss_;
}
inline ::PS::LossConfig* AppConfig::release_loss() {
  clear_has_loss();
  ::PS::LossConfig* temp = loss_;
  loss_ = NULL;
  return temp;
}
inline void AppConfig::set_allocated_loss(::PS::LossConfig* loss) {
  delete loss_;
  loss_ = loss;
  if (loss) {
    set_has_loss();
  } else {
    clear_has_loss();
  }
}

// optional .PS.PenaltyConfig penalty = 21;
inline bool AppConfig::has_penalty() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void AppConfig::set_has_penalty() {
  _has_bits_[0] |= 0x00000080u;
}
inline void AppConfig::clear_has_penalty() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void AppConfig::clear_penalty() {
  if (penalty_ != NULL) penalty_->::PS::PenaltyConfig::Clear();
  clear_has_penalty();
}
inline const ::PS::PenaltyConfig& AppConfig::penalty() const {
  return penalty_ != NULL ? *penalty_ : *default_instance_->penalty_;
}
inline ::PS::PenaltyConfig* AppConfig::mutable_penalty() {
  set_has_penalty();
  if (penalty_ == NULL) penalty_ = new ::PS::PenaltyConfig;
  return penalty_;
}
inline ::PS::PenaltyConfig* AppConfig::release_penalty() {
  clear_has_penalty();
  ::PS::PenaltyConfig* temp = penalty_;
  penalty_ = NULL;
  return temp;
}
inline void AppConfig::set_allocated_penalty(::PS::PenaltyConfig* penalty) {
  delete penalty_;
  penalty_ = penalty;
  if (penalty) {
    set_has_penalty();
  } else {
    clear_has_penalty();
  }
}

// optional .PS.LearnerConfig learner = 30;
inline bool AppConfig::has_learner() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void AppConfig::set_has_learner() {
  _has_bits_[0] |= 0x00000100u;
}
inline void AppConfig::clear_has_learner() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void AppConfig::clear_learner() {
  if (learner_ != NULL) learner_->::PS::LearnerConfig::Clear();
  clear_has_learner();
}
inline const ::PS::LearnerConfig& AppConfig::learner() const {
  return learner_ != NULL ? *learner_ : *default_instance_->learner_;
}
inline ::PS::LearnerConfig* AppConfig::mutable_learner() {
  set_has_learner();
  if (learner_ == NULL) learner_ = new ::PS::LearnerConfig;
  return learner_;
}
inline ::PS::LearnerConfig* AppConfig::release_learner() {
  clear_has_learner();
  ::PS::LearnerConfig* temp = learner_;
  learner_ = NULL;
  return temp;
}
inline void AppConfig::set_allocated_learner(::PS::LearnerConfig* learner) {
  delete learner_;
  learner_ = learner;
  if (learner) {
    set_has_learner();
  } else {
    clear_has_learner();
  }
}

// optional .PS.BlockIteratorConfig block_iterator = 40;
inline bool AppConfig::has_block_iterator() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void AppConfig::set_has_block_iterator() {
  _has_bits_[0] |= 0x00000200u;
}
inline void AppConfig::clear_has_block_iterator() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void AppConfig::clear_block_iterator() {
  if (block_iterator_ != NULL) block_iterator_->::PS::BlockIteratorConfig::Clear();
  clear_has_block_iterator();
}
inline const ::PS::BlockIteratorConfig& AppConfig::block_iterator() const {
  return block_iterator_ != NULL ? *block_iterator_ : *default_instance_->block_iterator_;
}
inline ::PS::BlockIteratorConfig* AppConfig::mutable_block_iterator() {
  set_has_block_iterator();
  if (block_iterator_ == NULL) block_iterator_ = new ::PS::BlockIteratorConfig;
  return block_iterator_;
}
inline ::PS::BlockIteratorConfig* AppConfig::release_block_iterator() {
  clear_has_block_iterator();
  ::PS::BlockIteratorConfig* temp = block_iterator_;
  block_iterator_ = NULL;
  return temp;
}
inline void AppConfig::set_allocated_block_iterator(::PS::BlockIteratorConfig* block_iterator) {
  delete block_iterator_;
  block_iterator_ = block_iterator;
  if (block_iterator) {
    set_has_block_iterator();
  } else {
    clear_has_block_iterator();
  }
}

// optional .PS.BlockCoordL1LRConfig block_coord_l1lr = 41;
inline bool AppConfig::has_block_coord_l1lr() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void AppConfig::set_has_block_coord_l1lr() {
  _has_bits_[0] |= 0x00000400u;
}
inline void AppConfig::clear_has_block_coord_l1lr() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void AppConfig::clear_block_coord_l1lr() {
  if (block_coord_l1lr_ != NULL) block_coord_l1lr_->::PS::BlockCoordL1LRConfig::Clear();
  clear_has_block_coord_l1lr();
}
inline const ::PS::BlockCoordL1LRConfig& AppConfig::block_coord_l1lr() const {
  return block_coord_l1lr_ != NULL ? *block_coord_l1lr_ : *default_instance_->block_coord_l1lr_;
}
inline ::PS::BlockCoordL1LRConfig* AppConfig::mutable_block_coord_l1lr() {
  set_has_block_coord_l1lr();
  if (block_coord_l1lr_ == NULL) block_coord_l1lr_ = new ::PS::BlockCoordL1LRConfig;
  return block_coord_l1lr_;
}
inline ::PS::BlockCoordL1LRConfig* AppConfig::release_block_coord_l1lr() {
  clear_has_block_coord_l1lr();
  ::PS::BlockCoordL1LRConfig* temp = block_coord_l1lr_;
  block_coord_l1lr_ = NULL;
  return temp;
}
inline void AppConfig::set_allocated_block_coord_l1lr(::PS::BlockCoordL1LRConfig* block_coord_l1lr) {
  delete block_coord_l1lr_;
  block_coord_l1lr_ = block_coord_l1lr;
  if (block_coord_l1lr) {
    set_has_block_coord_l1lr();
  } else {
    clear_has_block_coord_l1lr();
  }
}

// -------------------------------------------------------------------

// DataConfig

// required .PS.DataConfig.DataFormat format = 1;
inline bool DataConfig::has_format() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DataConfig::set_has_format() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DataConfig::clear_has_format() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DataConfig::clear_format() {
  format_ = 1;
  clear_has_format();
}
inline ::PS::DataConfig_DataFormat DataConfig::format() const {
  return static_cast< ::PS::DataConfig_DataFormat >(format_);
}
inline void DataConfig::set_format(::PS::DataConfig_DataFormat value) {
  assert(::PS::DataConfig_DataFormat_IsValid(value));
  set_has_format();
  format_ = value;
}

// repeated string files = 2;
inline int DataConfig::files_size() const {
  return files_.size();
}
inline void DataConfig::clear_files() {
  files_.Clear();
}
inline const ::std::string& DataConfig::files(int index) const {
  return files_.Get(index);
}
inline ::std::string* DataConfig::mutable_files(int index) {
  return files_.Mutable(index);
}
inline void DataConfig::set_files(int index, const ::std::string& value) {
  files_.Mutable(index)->assign(value);
}
inline void DataConfig::set_files(int index, const char* value) {
  files_.Mutable(index)->assign(value);
}
inline void DataConfig::set_files(int index, const char* value, size_t size) {
  files_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* DataConfig::add_files() {
  return files_.Add();
}
inline void DataConfig::add_files(const ::std::string& value) {
  files_.Add()->assign(value);
}
inline void DataConfig::add_files(const char* value) {
  files_.Add()->assign(value);
}
inline void DataConfig::add_files(const char* value, size_t size) {
  files_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
DataConfig::files() const {
  return files_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
DataConfig::mutable_files() {
  return &files_;
}

// optional .PS.PbRange range = 3;
inline bool DataConfig::has_range() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DataConfig::set_has_range() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DataConfig::clear_has_range() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DataConfig::clear_range() {
  if (range_ != NULL) range_->::PS::PbRange::Clear();
  clear_has_range();
}
inline const ::PS::PbRange& DataConfig::range() const {
  return range_ != NULL ? *range_ : *default_instance_->range_;
}
inline ::PS::PbRange* DataConfig::mutable_range() {
  set_has_range();
  if (range_ == NULL) range_ = new ::PS::PbRange;
  return range_;
}
inline ::PS::PbRange* DataConfig::release_range() {
  clear_has_range();
  ::PS::PbRange* temp = range_;
  range_ = NULL;
  return temp;
}
inline void DataConfig::set_allocated_range(::PS::PbRange* range) {
  delete range_;
  range_ = range;
  if (range) {
    set_has_range();
  } else {
    clear_has_range();
  }
}

// -------------------------------------------------------------------

// ParameterInitConfig

// optional .PS.ParameterInitConfig.Type type = 1 [default = ZERO];
inline bool ParameterInitConfig::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParameterInitConfig::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParameterInitConfig::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParameterInitConfig::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::PS::ParameterInitConfig_Type ParameterInitConfig::type() const {
  return static_cast< ::PS::ParameterInitConfig_Type >(type_);
}
inline void ParameterInitConfig::set_type(::PS::ParameterInitConfig_Type value) {
  assert(::PS::ParameterInitConfig_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional double random_std = 2 [default = 1];
inline bool ParameterInitConfig::has_random_std() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ParameterInitConfig::set_has_random_std() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ParameterInitConfig::clear_has_random_std() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ParameterInitConfig::clear_random_std() {
  random_std_ = 1;
  clear_has_random_std();
}
inline double ParameterInitConfig::random_std() const {
  return random_std_;
}
inline void ParameterInitConfig::set_random_std(double value) {
  set_has_random_std();
  random_std_ = value;
}

// -------------------------------------------------------------------

// BlockIteratorConfig

// optional int64 example_block_size = 1 [default = -1];
inline bool BlockIteratorConfig::has_example_block_size() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BlockIteratorConfig::set_has_example_block_size() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BlockIteratorConfig::clear_has_example_block_size() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BlockIteratorConfig::clear_example_block_size() {
  example_block_size_ = GOOGLE_LONGLONG(-1);
  clear_has_example_block_size();
}
inline ::google::protobuf::int64 BlockIteratorConfig::example_block_size() const {
  return example_block_size_;
}
inline void BlockIteratorConfig::set_example_block_size(::google::protobuf::int64 value) {
  set_has_example_block_size();
  example_block_size_ = value;
}

// optional float feature_block_ratio = 2 [default = 0];
inline bool BlockIteratorConfig::has_feature_block_ratio() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BlockIteratorConfig::set_has_feature_block_ratio() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BlockIteratorConfig::clear_has_feature_block_ratio() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BlockIteratorConfig::clear_feature_block_ratio() {
  feature_block_ratio_ = 0;
  clear_has_feature_block_ratio();
}
inline float BlockIteratorConfig::feature_block_ratio() const {
  return feature_block_ratio_;
}
inline void BlockIteratorConfig::set_feature_block_ratio(float value) {
  set_has_feature_block_ratio();
  feature_block_ratio_ = value;
}

// optional bool random_feature_block_order = 3 [default = true];
inline bool BlockIteratorConfig::has_random_feature_block_order() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BlockIteratorConfig::set_has_random_feature_block_order() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BlockIteratorConfig::clear_has_random_feature_block_order() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BlockIteratorConfig::clear_random_feature_block_order() {
  random_feature_block_order_ = true;
  clear_has_random_feature_block_order();
}
inline bool BlockIteratorConfig::random_feature_block_order() const {
  return random_feature_block_order_;
}
inline void BlockIteratorConfig::set_random_feature_block_order(bool value) {
  set_has_random_feature_block_order();
  random_feature_block_order_ = value;
}

// optional int32 max_pass_of_data = 8 [default = 10];
inline bool BlockIteratorConfig::has_max_pass_of_data() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BlockIteratorConfig::set_has_max_pass_of_data() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BlockIteratorConfig::clear_has_max_pass_of_data() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BlockIteratorConfig::clear_max_pass_of_data() {
  max_pass_of_data_ = 10;
  clear_has_max_pass_of_data();
}
inline ::google::protobuf::int32 BlockIteratorConfig::max_pass_of_data() const {
  return max_pass_of_data_;
}
inline void BlockIteratorConfig::set_max_pass_of_data(::google::protobuf::int32 value) {
  set_has_max_pass_of_data();
  max_pass_of_data_ = value;
}

// optional int32 max_block_delay = 10 [default = 0];
inline bool BlockIteratorConfig::has_max_block_delay() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BlockIteratorConfig::set_has_max_block_delay() {
  _has_bits_[0] |= 0x00000010u;
}
inline void BlockIteratorConfig::clear_has_max_block_delay() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void BlockIteratorConfig::clear_max_block_delay() {
  max_block_delay_ = 0;
  clear_has_max_block_delay();
}
inline ::google::protobuf::int32 BlockIteratorConfig::max_block_delay() const {
  return max_block_delay_;
}
inline void BlockIteratorConfig::set_max_block_delay(::google::protobuf::int32 value) {
  set_has_max_block_delay();
  max_block_delay_ = value;
}

// optional double epsilon = 11 [default = 0.0001];
inline bool BlockIteratorConfig::has_epsilon() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void BlockIteratorConfig::set_has_epsilon() {
  _has_bits_[0] |= 0x00000020u;
}
inline void BlockIteratorConfig::clear_has_epsilon() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void BlockIteratorConfig::clear_epsilon() {
  epsilon_ = 0.0001;
  clear_has_epsilon();
}
inline double BlockIteratorConfig::epsilon() const {
  return epsilon_;
}
inline void BlockIteratorConfig::set_epsilon(double value) {
  set_has_epsilon();
  epsilon_ = value;
}

// -------------------------------------------------------------------

// BlockCoordL1LRConfig

// optional double delta_init_value = 1 [default = 1];
inline bool BlockCoordL1LRConfig::has_delta_init_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BlockCoordL1LRConfig::set_has_delta_init_value() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BlockCoordL1LRConfig::clear_has_delta_init_value() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BlockCoordL1LRConfig::clear_delta_init_value() {
  delta_init_value_ = 1;
  clear_has_delta_init_value();
}
inline double BlockCoordL1LRConfig::delta_init_value() const {
  return delta_init_value_;
}
inline void BlockCoordL1LRConfig::set_delta_init_value(double value) {
  set_has_delta_init_value();
  delta_init_value_ = value;
}

// optional double delta_max_value = 2 [default = 5];
inline bool BlockCoordL1LRConfig::has_delta_max_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BlockCoordL1LRConfig::set_has_delta_max_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BlockCoordL1LRConfig::clear_has_delta_max_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BlockCoordL1LRConfig::clear_delta_max_value() {
  delta_max_value_ = 5;
  clear_has_delta_max_value();
}
inline double BlockCoordL1LRConfig::delta_max_value() const {
  return delta_max_value_;
}
inline void BlockCoordL1LRConfig::set_delta_max_value(double value) {
  set_has_delta_max_value();
  delta_max_value_ = value;
}

// optional bool enable_multi_thread = 4 [default = false];
inline bool BlockCoordL1LRConfig::has_enable_multi_thread() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BlockCoordL1LRConfig::set_has_enable_multi_thread() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BlockCoordL1LRConfig::clear_has_enable_multi_thread() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BlockCoordL1LRConfig::clear_enable_multi_thread() {
  enable_multi_thread_ = false;
  clear_has_enable_multi_thread();
}
inline bool BlockCoordL1LRConfig::enable_multi_thread() const {
  return enable_multi_thread_;
}
inline void BlockCoordL1LRConfig::set_enable_multi_thread(bool value) {
  set_has_enable_multi_thread();
  enable_multi_thread_ = value;
}

// optional double kkt_filter_threshold_ratio = 10 [default = 10];
inline bool BlockCoordL1LRConfig::has_kkt_filter_threshold_ratio() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BlockCoordL1LRConfig::set_has_kkt_filter_threshold_ratio() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BlockCoordL1LRConfig::clear_has_kkt_filter_threshold_ratio() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BlockCoordL1LRConfig::clear_kkt_filter_threshold_ratio() {
  kkt_filter_threshold_ratio_ = 10;
  clear_has_kkt_filter_threshold_ratio();
}
inline double BlockCoordL1LRConfig::kkt_filter_threshold_ratio() const {
  return kkt_filter_threshold_ratio_;
}
inline void BlockCoordL1LRConfig::set_kkt_filter_threshold_ratio(double value) {
  set_has_kkt_filter_threshold_ratio();
  kkt_filter_threshold_ratio_ = value;
}

// optional int64 auc_goodness = 12 [default = 1000];
inline bool BlockCoordL1LRConfig::has_auc_goodness() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BlockCoordL1LRConfig::set_has_auc_goodness() {
  _has_bits_[0] |= 0x00000010u;
}
inline void BlockCoordL1LRConfig::clear_has_auc_goodness() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void BlockCoordL1LRConfig::clear_auc_goodness() {
  auc_goodness_ = GOOGLE_LONGLONG(1000);
  clear_has_auc_goodness();
}
inline ::google::protobuf::int64 BlockCoordL1LRConfig::auc_goodness() const {
  return auc_goodness_;
}
inline void BlockCoordL1LRConfig::set_auc_goodness(::google::protobuf::int64 value) {
  set_has_auc_goodness();
  auc_goodness_ = value;
}

// -------------------------------------------------------------------

// LossConfig

// required .PS.LossConfig.Type type = 1;
inline bool LossConfig::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LossConfig::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LossConfig::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LossConfig::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::PS::LossConfig_Type LossConfig::type() const {
  return static_cast< ::PS::LossConfig_Type >(type_);
}
inline void LossConfig::set_type(::PS::LossConfig_Type value) {
  assert(::PS::LossConfig_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// -------------------------------------------------------------------

// LearnerConfig

// required .PS.LearnerConfig.Type type = 1;
inline bool LearnerConfig::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LearnerConfig::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LearnerConfig::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LearnerConfig::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::PS::LearnerConfig_Type LearnerConfig::type() const {
  return static_cast< ::PS::LearnerConfig_Type >(type_);
}
inline void LearnerConfig::set_type(::PS::LearnerConfig_Type value) {
  assert(::PS::LearnerConfig_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional float learning_rate = 2 [default = 1];
inline bool LearnerConfig::has_learning_rate() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LearnerConfig::set_has_learning_rate() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LearnerConfig::clear_has_learning_rate() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LearnerConfig::clear_learning_rate() {
  learning_rate_ = 1;
  clear_has_learning_rate();
}
inline float LearnerConfig::learning_rate() const {
  return learning_rate_;
}
inline void LearnerConfig::set_learning_rate(float value) {
  set_has_learning_rate();
  learning_rate_ = value;
}

// -------------------------------------------------------------------

// AggGradLearnerArg

// optional float learning_rate = 1 [default = 1];
inline bool AggGradLearnerArg::has_learning_rate() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AggGradLearnerArg::set_has_learning_rate() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AggGradLearnerArg::clear_has_learning_rate() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AggGradLearnerArg::clear_learning_rate() {
  learning_rate_ = 1;
  clear_has_learning_rate();
}
inline float AggGradLearnerArg::learning_rate() const {
  return learning_rate_;
}
inline void AggGradLearnerArg::set_learning_rate(float value) {
  set_has_learning_rate();
  learning_rate_ = value;
}

// -------------------------------------------------------------------

// PenaltyConfig

// required .PS.PenaltyConfig.Type type = 1;
inline bool PenaltyConfig::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PenaltyConfig::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PenaltyConfig::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PenaltyConfig::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::PS::PenaltyConfig_Type PenaltyConfig::type() const {
  return static_cast< ::PS::PenaltyConfig_Type >(type_);
}
inline void PenaltyConfig::set_type(::PS::PenaltyConfig_Type value) {
  assert(::PS::PenaltyConfig_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// required float coefficient = 2 [default = 0];
inline bool PenaltyConfig::has_coefficient() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PenaltyConfig::set_has_coefficient() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PenaltyConfig::clear_has_coefficient() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PenaltyConfig::clear_coefficient() {
  coefficient_ = 0;
  clear_has_coefficient();
}
inline float PenaltyConfig::coefficient() const {
  return coefficient_;
}
inline void PenaltyConfig::set_coefficient(float value) {
  set_has_coefficient();
  coefficient_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PS

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PS::AppConfig_AppType>() {
  return ::PS::AppConfig_AppType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PS::DataConfig_DataFormat>() {
  return ::PS::DataConfig_DataFormat_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PS::ParameterInitConfig_Type>() {
  return ::PS::ParameterInitConfig_Type_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PS::LossConfig_Type>() {
  return ::PS::LossConfig_Type_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PS::LearnerConfig_Type>() {
  return ::PS::LearnerConfig_Type_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PS::PenaltyConfig_Type>() {
  return ::PS::PenaltyConfig_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fconfig_2eproto__INCLUDED
